### ISSUE TITLE
Finding difficult to make it work with Python3

### ISSUE THREAD

**Issue by ghost** [Vinothsuku/vizdxp#1]
Thanks for your effort to bring in Vizdxp. Appreciate your due diligence in building this framework.

My issue is about making it work with Python3 which seems to be not working.

**Comment by DikshithAC** [comment]
ng-2.4.7 pyrsistent-0.16.0 pyzmq-19.0.2 retrying-1.3.3 streamlit-0.65.2 terminado-0.8.3 testpath-0.4.4 toml-0.10.1 toolz-0.10.0 tornado-6.0.4 traitlets-4.3.3 tzlocal-2.1 validators-0.18.0 vizdxp-0.0.5 watchdog-0.10.3 wcwidth-0.2.5 webencodings-0.5.1 widgetsnbextension-3.5.1
WARNING: You are using pip version 20.1.1; however, version 20.2.2 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -m pip install --upgrade pip' command.
DAdoor:~ dixitac$ pip install --upgrade pip
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pip
  Downloading https://files.pythonhosted.org/packages/5a/4a/39400ff9b36e719bdf8f31c99fe1fa7842a42fa77432e584f707a5080063/pip-20.2.2-py2.py3-none-any.whl (1.5MB)
     |████████████████████████████████| 1.5MB 996kB/s
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/pip-19.2.3-py2.7.egg/EGG-INFO/PKG-INFO'
Consider using the `--user` option or check the permissions.

**Comment by ghost** [comment]
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting vizdxp
  ERROR: Could not find a version that satisfies the requirement vizdxp (from versions: none)
ERROR: No matching distribution found for vizdxp

**Comment by ghost** [comment]
close

**Comment by Vinothsuku** [comment]
Thanks @DikshithAC for trying vizdxp. Hopefully you could try the package successfully, if you are facing any other issues, pls log it. Will do the needful
